<?php
/**
 * @file
 * Ting DK5 settings module.
 */

/**
 * Implements hook_menu().
 */
function ting_dk5_menu() {
  $items = array();

  $items['admin/config/ting/dk5'] = array(
    'title' => 'Ting DK5 Settings',
    'description' => 'Configure DK5 settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_dk5_settings_admin_form'),
    'access arguments' => array('administer ting_dk5 settings'),
    'file' => 'ting_dk5.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ting_dk5_permission() {
  return array(
    'administer ting_dk5 settings' => array(
      'title' => t('Administer Ting DK5 settings'),
    ),
  );
}

/**
 * Define default display settings for various modes.
 *
 * @param string $mode
 *   View mode.
 *
 * @return array
 *   Field instance view mode settings.
 */
function ting_dk5_view_mode_settings($mode) {
  $modes = array();

  $modes['default'] = array(
    'label' => 'inline',
    'module' => 'ting_material_details',
    'settings' => array(),
    'type' => 'ting_details_linked_dk5',
    'weight' => 50,
  );

  $modes['search_result'] = array(
    'label' => 'hidden',
    'module' => 'ting_material_details',
    'settings' => array(),
    'type' => 'ting_details_linked_dk5',
    'weight' => 20,
  );

  $modes['collection_list'] = array(
    'label' => 'hidden',
    'module' => 'ting_material_details',
    'settings' => array(),
    'type' => 'ting_details_linked_dk5',
    'weight' => 7,
  );

  $modes['_hidden_'] = array(
    'label' => 'hidden',
    'settings' => array(),
    'type' => 'hidden',
    'weight' => 99,
  );

  return isset($modes[$mode]) ? $modes[$mode] : array();
}

/**
 * Implements hook_entity_view().
 */
function ting_dk5_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type != 'ting_object') {
    return;
  }

  $group = FALSE;
  if ($view_mode == 'default') {
    $group = 'group_ting_object_right_column';
  }
  elseif ($view_mode == 'search_result') {
    $group = 'group_ting_right_col_search';
  }
  elseif ($view_mode == 'collection_list') {
    $group = 'group_ting_right_col_collection';
  }

  if ($group) {
    $entity->content['#group_children']['ting_details_classification'] = $group;
  }
}
